docs/_templates/layout.html
docs/_templates/theme_variables.jinja

There was no way to go back to the main Partners docs from the ionq docs.  This fixes that in the main nav bar. 
Also adds tutorials and resources instead of "Learning Resources" to better mirror main docs navigation.

Updates to nav bar

---

qiskit_ionq/ionq_job.py
test/ionq_job/test_job.py

Because the ionq simulator has some floating point weirdness, we re-normalize the results to make sure that all of the probabilities in the random sampling add up to one.
When there is one output state where p=1 in the simulator output, numpy freaks out when we're normalizing, because 1 is an integer and it's not cool with that.
forcibly casting all of the states to floats beforehand fixes this.

fix and test against sumulator output with integers

---

README.md
docs/guides/install.rst
requirements.txt

Bump version pin to `qiskit-terra>=0.17.4`, to prevent legacy aqua/framework bugs.

Bump terra version pin and docs

---

qiskit_ionq/ionq_provider.py

Ideally, we can dynamically fetch the backends and have the correct qubit count. This does not do that, but simply unblocks use of more specific targets.

Support more backends by doing prefix filtering

---

qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_provider.py
qiskit_ionq/version.py
test/conftest.py
test/ionq_job/test_job.py
test/ionq_provider/test_backend_service.py

This fixes a bug in the behavior for 0.2.0, which accepted more specific backend names, but did not pass them server-side
Planning to release as 0.2.1 if there are no objections.

Pipe target through the qiskit stack, add test

---

qiskit_ionq/ionq_backend.py
qiskit_ionq/version.py

If a particular circuit is run on hardware that does not support that specific size, it will be rejected server-side.
This is a bit of a cludge around dynamic backend fetching, once that is completed, we shouldn't be dependent on these SDK-specific caps.

Raise n_qubits to max IonQ provides across all QPU backends

---

qiskit_ionq/exceptions.py
test/test_exceptions.py

This was overriding the message defined in the class, so that users would see
IonQGateError(gate_name='foo')
instead of
IonQGateError('gate 'foo' not supported on IonQ backends. Please use the qiskit.transpile method or manually rewrite to remove the gate')
This way, developers will see the former and users the latter, as was originally intended.

Change overriden method in IonQGateError to __repr__

---

qiskit_ionq/__init__.py
qiskit_ionq/exceptions.py
qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_gates.py
qiskit_ionq/ionq_job.py
qiskit_ionq/ionq_provider.py
qiskit_ionq/ionq_result.py
qiskit_ionq/version.py
test/conftest.py
test/helpers/test_qiskit_to_ionq.py
test/ionq_gates/__init__.py
test/ionq_gates/test_gates.py
test/ionq_job/test_job.py
test/ionq_provider/test_backend_service.py
test/test_exceptions.py

IonQ Native gates support in Qiskit
Bump to 0.3.0
This PR allows configuration of a 'lang' when creating an IonQBackend, which controls the basis gates used. "qis" is the existing default, and "native" allows for programming with GPI, GPI2 and MS gates.
These gates are also defined in this PR, along with matrix representations

Add gate definitions and language selection for Native Gates

---

test/ionq_gates/test_gates.py

https://ionq.com/docs/getting-started-with-native-gates
Both as a sanity check for the unitaries defined here, and as a test of the statements there. Win-win!

Add tests for published equivalences

---

qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_provider.py

Also update to use the v0.2 base URL
There were a few issues with calibration(), mainly:
1. list calibrations endpoint no longer exists
2. code that was ported to raise_for_status was ported incorrectly, doubly breaking it (mea culpa on this one, I think)
This was tested manually, we'll have to add this to our internal integration testing to avoid this kind of breakage, which I can do as a followup

Fix calibration() method

---

qiskit_ionq/exceptions.py

bad_gateway (502 response status) has been seen in production causing issues retrieving job results in scripts because the error is not retried.
502 should be safe to retry similarly to other 5xx responses (though we will need to make sure these retries do not cause duplicate submission API-side, time to start writing [etags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)?)

_RETRIABLE_STATUS_CODES += bad_gateway

---

qiskit_ionq/exceptions.py
test/test_exceptions.py

Includes full http response in expections
includes this `http_response` [alongside](https://github.com/Qiskit-Partners/qiskit-ionq/blob/c757237c76bacf31ebf3391f7dd1ee86c57c5b23/qiskit_ionq/exceptions.py#L157-L159) `error_type`. alternatively we can just show the `http_response`.

Include full http response on exception

---

qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
test/helpers/test_qiskit_to_ionq.py

Follow [Qiskit convention](https://qiskit.org/documentation/stubs/qiskit_aer.AerSimulator.run.html#qiskit-aer-aersimulator-run) of specifying options in `run(..., **kwargs)`.
Can invoke with
```python
provider = IonQProvider()
backend = provider.get_backend("ionq_simulator")
job = backend.run(qc, noise_model="ideal")
print(job.get_counts())
```

Adds noise_model to override in run method

---

qiskit_ionq/helpers.py
test/helpers/test_qiskit_to_ionq.py

Updates job submissions to use v0.3 spec. https://docs.ionq.com/v0.3
```python
ionq_json = {
"lang": "json",
"body": {
...
},
...
}
```
to
```python
ionq_json = {
"input": {
"format": "ionq.circuit.v0",
...
},
...
}
```

Update request payload to API v0.3

---

README.md
qiskit_ionq/__init__.py
qiskit_ionq/constants.py
qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_job.py
test/conftest.py
test/helpers/test_gate_serialization.py
test/helpers/test_qiskit_to_ionq.py
test/ionq_backend/test_base_backend.py
test/ionq_job/test_job.py
test/ionq_provider/test_backend_service.py

Renames symmetrization to debiasing, updates the v0.3 backend naming scheme, and adds a `extra_request_payload` for specifying post / get parameters

rename debiasing + backend

---

qiskit_ionq/helpers.py
test/helpers/test_qiskit_to_ionq.py

Logic was assuming that for gates with 1 input that input was 'phase' which is not true for ZZ, which just has 'theta'

Fixup serialization of ZZ gate

---

qiskit_ionq/ionq_client.py

only uses `exceptions.IonQAPIError.raise_for_status(res)` from decorated methods

don't raise exception from non-decorated method

---

qiskit_ionq/helpers.py
qiskit_ionq/version.py
test/helpers/test_qiskit_to_ionq.py
tox.ini

alias bug for gates:
- ccx -> x
- csx -> v
- sdg -> si
- sx -> v
- sxdg -> vi
- tdg -> ti
- toffoli -> x
passes in python 3.9 but fails with python 3.11
```shell
FAILED test/helpers/test_gate_serialization.py::test_individual_instruction_serialization[ccx-gate_args0-expected_serialization0] - AssertionError: assert [{'gate': 'cx', 'targets': [2], 'controls': [0, 1]}] == [{'gate': 'x', 'targets': [2], 'controls': [0, 1]}]
FAILED test/helpers/test_gate_serialization.py::test_individual_instruction_serialization[csx-gate_args10-expected_serialization10] - AssertionError: assert [{'gate': 'sx', 'targets': [1], 'controls': [0]}] == [{'gate': 'v', 'targets': [1], 'controls': [0]}]
FAILED test/helpers/test_gate_serialization.py::test_individual_instruction_serialization[sdg-gate_args37-expected_s …
```

fix incorrect gate aliasing

---

qiskit_ionq/ionq_job.py

can run
```python
job = backend.run(qc)
results = job.result(wait=1)  # default is 5 seconds
```
can get results faster

include kwargs to use wait in result

---

qiskit_ionq/ionq_provider.py

when using the `IonQProvider`, allow for short names / qpu names
enables this:
```python
provider = IonQProvider()
backend = provider.get_backend("simulator")
backend = provider.get_backend("qpu.aria-1")
```

allow shorthand names for ionq backends

---

qiskit_ionq/exceptions.py
qiskit_ionq/helpers.py

We're raising this limit considerable server-side so we expect both not to hit the limit, and to have a reasonable error message from the API if it does so. 
Either way, the client checking the limit is no longer necessary and impedes further raising the limit in a way that benefits all existing users.

Remove client-side metadata length check

---

qiskit_ionq/version.py
requirements.txt

Qiskit 1.0 works, but there is nothing preventing older library versions, and we'd prefer to support both for some period to allow for library compatibility flexibility

Change qiskit dependency to allow 0.4+

---

docs/conf.py
qiskit_ionq/__init__.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_job.py
qiskit_ionq/ionq_provider.py
qiskit_ionq/version.py
requirements-docs.txt
requirements-test.txt
requirements.txt

```python
print(job._metadata)
```
```python
backend.cancel_job('9a36b191-d8be-4b77-abcc-ec1ef0ac15d2')
backend.cancel_jobs(['6fb62d08-4e55-4fbd-8874-b01453290730', '37635b2b-994b-42f4-8d65-c4133328f95d'])
```
plus remove qiskit dep (warn if not installed)

add backend cancel job methods and save metadata

---

qiskit_ionq/ionq_gates.py

Fixes #162 ; current matrix is big-endian, while Qiskit is little-endian.

Correct MS gate matrix

---

.pylintrc
README.md
qiskit_ionq/helpers.py
qiskit_ionq/ionq_job.py
qiskit_ionq/version.py
requirements.txt
test/conftest.py
test/ionq_backend/test_base_backend.py
test/ionq_job/test_job.py

creates `children_status` method for reporting child statuses:
```python
status = job.status(detailed=True)
print(status)
```
```python
{'total': 2, 'completed': 0, 'failed': 0, 'percentage_complete': 0.0, 'statuses': [<JobStatus.QUEUED: 'job is queued'>, <JobStatus.QUEUED: 'job is queued'>]}
{'total': 2, 'completed': 1, 'failed': 0, 'percentage_complete': 0.5, 'statuses': [<JobStatus.QUEUED: 'job is queued'>, <JobStatus.DONE: 'job has successfully run'>]}
{'total': 2, 'completed': 2, 'failed': 0, 'percentage_complete': 1.0, 'statuses': [<JobStatus.DONE: 'job has successfully run'>, <JobStatus.DONE: 'job has successfully run'>]}
```

add method to display child progress

---

qiskit_ionq/version.py
requirements.txt

As noted in qiskit's docs, it's potentially problematic to upgrade a pre-existing python environment to qiskit 1.0.0.
Given that we don't require any 1.0.0 functionality (i.e, are currently cross-compatible), we can relax the versioning requirement and just require qiskit.

Remove qiskit > 1.0.0 requirement

---

qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_provider.py
qiskit_ionq/version.py
test/conftest.py
test/ionq_backend/test_base_backend.py

temporary solution before migrating to [backendv2](https://docs.quantum.ibm.com/api/qiskit/qiskit.providers.models.BackendConfiguration)
update `n_qubits` to `36`.
set EM from backend options

get num of qubits from api or use 36 and fix EM sampler

---

qiskit_ionq/__init__.py
qiskit_ionq/exceptions.py
qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_equivalence_library.py
qiskit_ionq/ionq_gates.py
qiskit_ionq/ionq_job.py
qiskit_ionq/ionq_provider.py
setup.py
tox.ini

Add type annotations to part of the public API

---

qiskit_ionq/exceptions.py
test/test_exceptions.py

The bug can be reproduced with:
```python
from qiskit_ionq.exceptions import IonQAPIError
import pickle
err = IonQAPIError(message='hi', status_code=400, headers='hi', body='hi', error_type='hi')
pickle.loads(pickle.dumps(err))
```
which gives:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 4
2 import pickle
3 err = IonQAPIError(message='hi', status_code=400, headers='hi', body='hi', error_type='hi')
----> 4 pickle.loads(pickle.dumps(err))
TypeError: IonQAPIError.__init__() missing 4 required positional arguments: 'status_code', 'headers', 'body', and 'error_type'
```

Fix bug regarding serializing custom exceptions which occurs in multiprocessing context

---

qiskit_ionq/helpers.py
test/helpers/test_helpers.py

the simulator doesn't have accessible qubit defaults, so we need to manually add this
prevents a warning from the backend initialization

fix default qubit warning for simulator

---

qiskit_ionq/helpers.py
qiskit_ionq/version.py
test/helpers/test_gate_serialization.py

instead of checking against a tuple, check the quality of the gate
`if the gate has multiple targets and no control qubits`

catch all multi target uncontrolled gates

---

qiskit_ionq/version.py
requirements-docs.txt
requirements-test.txt
requirements.txt

qiskit 2.0 breaks until we refactor from V1 classes
restrict to qiskit 1.0 until work on V2 is done

restrict qiskit version to 1.x

---

docs/conf.py
example/example.ipynb

The documentation source of truth is moving to https://quantum.cloud.ibm.com/.

Update intersphinx mapping and other URLs pointing to IQP Classic

---

qiskit_ionq/exceptions.py
qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/version.py
test/helpers/test_helpers.py

- adds ygate
- fixes `MCX` and `MCPhase` gates
```python
from qiskit import QuantumCircuit, transpile
from qiskit.circuit.library import PauliEvolutionGate
from qiskit.quantum_info import SparsePauliOp
from qiskit_ionq import IonQProvider
simulator_backend = IonQProvider().get_backend("simulator", gateset="qis")
operator = SparsePauliOp(["XX", "YY", "ZZ"], coeffs=[0.1, 0.2, 0.3])
evo = PauliEvolutionGate(operator, time=0.4)
circuit = QuantumCircuit(9)
circuit.append(evo, [0, 1])
circuit.mcx(list(range(7)), 8)
circuit.mcp(0.5, list(range(7)), 8)
t_circuit = transpile(
circuit,
backend=simulator_backend,
optimization_level=1,
)
t_circuit.draw("mpl")
```

Add YGate and update parameters for gate instructions in IonQBackend
