qiskit-community/qiskit-ionq

README.md
docs/guides/install.rst
qiskit_ionq/helpers.py
requirements.txt

Pin to `qiskit>=0.25.0` to avoid result model instantiation errors.
Without this, you get something like: 
```
TypeError: __init__() got an unexpected keyword argument <some_keyword_arg>
```

Pin qiskit version to avoid result processing errors

---

README.md
qiskit_ionq/helpers.py
requirements.txt

Fixed a few typos and added pytest setup instructions.

Setup tips

---

qiskit_ionq/ionq_gates.py

Mistakenly added while I was trying to sneak some last minute fixes in without PRs (I have learned my lesson)

Fix trailing whitespace

---

qiskit_ionq/helpers.py
qiskit_ionq/ionq_client.py
requirements.txt
test/helpers/test_helpers.py

Added User-Agent string.
closes #91 
An observation, the naming of User-Agent strings is not [standardised](https://webaim.org/blog/user-agent-string-history/).

Added User-Agent header [unitaryhack]

---

qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/version.py

Going to pre-release this to unblock some local folks

Add job_settings to set arbitrary API fields for new features

---

qiskit_ionq/helpers.py
qiskit_ionq/ionq_gates.py
test/helpers/test_qiskit_to_ionq.py
test/ionq_gates/test_gates.py
test/ionq_job/test_job.py

MS Native Gate now supports an arbitrary theta angle.
It will default to 0.25 (equivalent to half PI), which is equivalent to the previous implementation of this gate.

Support new arbitrary angle param for MS Gate

---

qiskit_ionq/ionq_backend.py

Raise coupling map to 32

---

qiskit_ionq/ionq_backend.py
test/ionq_backend/test_base_backend.py

Emits a warning when a submitted circuit has no valid qubit->bit mappings.
```python
provider = IonQProvider()
backend = provider.get_backend("ionq_simulator")
qc = qiskit.QuantumCircuit(1, 1, name="null circuit")
qc.h(0)
job = backend.run(qc)
> /qiskit-ionq/qiskit_ionq/ionq_backend.py:359: UserWarning: Circuit null mappings is not measuring any qubits
```

Warn when a Qiskit circuit has null mappings for all registers

---

README.md
qiskit_ionq/__init__.py
qiskit_ionq/constants.py
qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_job.py
qiskit_ionq/ionq_result.py
test/helpers/test_qiskit_to_ionq.py
test/ionq_job/test_job.py

Add error_mitigation settings
Includes:
- Settings on job submission to enable/disable and configure symmetrization
- New results parameter to fetch results by different aggregation methods if job was symmetrized

add error_mitigation settings

---

qiskit_ionq/version.py

updates pip package to 0.4.0
1. update version
2. make matching github release (v0.4.0)

minor release bump (0.4.0.dev)

---

qiskit_ionq/version.py

Includes debiasing and updated backend naming scheme to the release.
- debias renaming pr

Releases the stable 0.4.0 version

---

.github/workflows/docs.yml
.github/workflows/main.yaml
.github/workflows/pr.yml
.github/workflows/release.yml

updates python version in build + tests
removes 3.7 and adds 3.11. uses 3.11 for building (latest lts as of now)

updates python for testing & building

---

qiskit_ionq/helpers.py

make documentation using `ionq_qpu` as backend work
defaults ionq_qpu to harmony.
todo: use cheapest available option as default

default ionq_qpu to ionq_qpu.harmony

---

qiskit_ionq/helpers.py
qiskit_ionq/version.py

fixes common issue from documentation
asap release

Update version.py to 0.4.1

---

qiskit_ionq/helpers.py
qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_job.py
test/helpers/test_qiskit_to_ionq.py
test/ionq_backend/test_base_backend.py
tox.ini

Add an extra_metadata argument to specify / filter on additional information
adds extra metadata + upgrades python testing to 3.10

Allow for additional metadata to be specified

---

qiskit_ionq/helpers.py
requirements-docs.txt

formats user-agent: info instead of user-agent: user-agent: info
also fixes doc build requirements

fix user-agent formatting

---

README.md
qiskit_ionq/__init__.py
qiskit_ionq/exceptions.py
qiskit_ionq/helpers.py
qiskit_ionq/ionq_gates.py
qiskit_ionq/version.py
test/helpers/test_gate_serialization.py
test/helpers/test_qiskit_to_ionq.py
test/ionq_gates/test_gates.py

adds `zz` gate to native gateset
uses [qiskit gate](https://qiskit.org/documentation/_modules/qiskit/circuit/library/standard_gates/rzz.html#RZZGate) for optional future changing

QTPF-4559 add zz to native gateset

---

.pylintrc
qiskit_ionq/ionq_client.py
test/ionq_job/test_job.py

try-catch block has been added around the network request to handle exceptions that can be retried

raise IonQRetriableError when get fails

---

.github/workflows/pr.yml

Adding the documentation as part of CI as an artifact

Add docs CI artifact

---

docs/conf.py
docs/index.rst
requirements-docs.txt

Updates to new Ecosystem theme.
For more information: https://github.com/Qiskit/qiskit_sphinx_theme/issues/232

Update Sphinx theme

---

qiskit_ionq/ionq_gates.py

The angle and phases are in units of turns, so the converison of 2*pi occurs in these places

Fixup unitary for ZZ (code & comment), MS (comment only)

---

qiskit_ionq/ionq_job.py

do not `**None`, instead `**{}`

map empty dict when none

---

qiskit_ionq/exceptions.py
qiskit_ionq/version.py

As is the case for ChunkedEncodingError

Handle cause.message being unset

---

README.md

changes outdated api key generation instructions
links to api key page instead of sales email

update api key instructions

---

qiskit_ionq/helpers.py
qiskit_ionq/version.py

use a safeencoder to parse any object passed in the job
uses the __string__ method if present otherwise calls repr

Add SafeEncoder class to handle non-JSON-safe objects

---

qiskit_ionq/ionq_backend.py
qiskit_ionq/version.py

sets number of qubits to 35 to handle larger circuits
applied to simulator and qpu

Update number of qubits to 35

---

qiskit_ionq/__init__.py
qiskit_ionq/version.py

use raise instead of warning

---

qiskit_ionq/version.py

stable release of qiskit v1 support

---

qiskit_ionq/ionq_provider.py
requirements.txt

can create a .env file and use project-specific `IONQ_API_KEY`.

add support for .env file loading keys

---

qiskit_ionq/version.py

updates to 0.5.1.dev0
release multicircuit support

0.5.1 dev patch release

---

qiskit_ionq/ionq_job.py

optimize `_build_counts` method and drop 0s from dict
speed up handling of large jobs

large jobs fail processing, so drop 0s

---

qiskit_ionq/ionq_backend.py
qiskit_ionq/ionq_equivalence_library.py
qiskit_ionq/ionq_gates.py
qiskit_ionq/version.py
requirements.txt
test/transpile_ionq_gates/test_transpile_ionq_gates.py

Fix transpiling to  IonQ native gates

---

qiskit_ionq/ionq_job.py

reported by [https://github.com/qiskit-community/qiskit-ionq/issues/183] and [https://github.com/qiskit-community/qiskit-ionq/pull/154#issuecomment-2259834170]
need to get `meas_mapped` for each child job

fixes qubit mapping bug

---

test/conftest.py
test/helpers/test_qiskit_to_ionq.py
test/ionq_job/test_job.py

ensures we dont break qubit mapping again

add test for meas_mapped

---

qiskit_ionq/helpers.py
test/helpers/test_qiskit_to_ionq.py

remove default qpu and noise model
remove deprecation warning and stop setting a default

Retire harmony

---

.github/workflows/main.yaml

Fixup 3.10 inclusion

---

.github/workflows/docs.yml
.github/workflows/main.yaml
.github/workflows/pr.yml
.github/workflows/release.yml
setup.py
tox.ini

Test on run CI on Python 3.12 by default and add classifier

---

.pre-commit-config.yaml
docs/conf.py
example/example.ipynb
qiskit_ionq/constants.py
qiskit_ionq/exceptions.py
qiskit_ionq/helpers.py
qiskit_ionq/ionq_client.py
qiskit_ionq/ionq_equivalence_library.py
qiskit_ionq/ionq_job.py
qiskit_ionq/ionq_provider.py
test/conftest.py
test/helpers/test_helpers.py
test/ionq_job/test_job.py
test/test_exceptions.py
test/test_mock.py
tools/verify_headers.py

Basically the same style as black but Ruff comes with many more features and is much faster.

Enable Ruff formatting and apply style

---

.github/workflows/docs.yml
.github/workflows/main.yaml
.github/workflows/pr.yml
.github/workflows/release.yml

deprecation for `actions/upload-artifact@v2` so this pr updates all the actions
```
actions/checkout@v4
actions/setup-python@v5
actions/upload-artifact@v4
```

update actions versions to latest major

---

.github/workflows/release.yml

pip install setuptools
fix release action

add setuptools to pip release

---

qiskit_ionq/version.py
test/test_exceptions.py

updates qiskit-ionq to 0.5.8
also varies the messages in the exception pickling test

vary exception strings and update patch release

---

.pre-commit-config.yaml
qiskit_ionq/helpers.py
qiskit_ionq/ionq_client.py
qiskit_ionq/version.py
requirements-docs.txt
requirements.txt
test/helpers/test_helpers.py

removes the retry dependency because of the py vulnerability. adds a custom retry decorator that does the same thing without external deps
https://github.com/invl/retry/issues/58

remove retry dependency

---

qiskit_ionq/helpers.py

dont show -1 more time(s)
infinite:
```python
UserWarning: Retrying retrieve_job after IonQRetriableError('Unknown error')
```
limited:
```python
UserWarning: Retrying retrieve_job 1 more time(s) after IonQRetriableError('Unknown error')
```

hide negative retry values

---

qiskit_ionq/helpers.py
qiskit_ionq/version.py

#164 changed the exceptions name. this pr fixes for the later prs

Fix exception variable

---

.github/workflows/docs.yml
.github/workflows/main.yaml
.github/workflows/pr.yml
.github/workflows/release.yml
qiskit_ionq/ionq_job.py
qiskit_ionq/version.py
setup.py
test/ionq_job/test_job.py
tox.ini

getting a canceled job doesn't fail
replace an exception with warning. use python 3.13

allow getting canceled jobs + use python 3.13

---

.github/workflows/main.yaml
.github/workflows/pr.yml

address pylint issue import collections.abc
https://github.com/pylint-dev/pylint/issues/10000

try python3.12 for linting

---

.pre-commit-config.yaml
qiskit_ionq/__init__.py
test/ionq_job/test_job.py

Enable Ruff linting and update pre-commit filters

---

.github/workflows/docs.yml

Documented at https://github.com/JamesIves/github-pages-deploy-action

Update to contents: write for pages
